"""init

Revision ID: 84c1ec898101
Revises: 
Create Date: 2019-05-08 14:42:17.417324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c1ec898101'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('noteContent', sa.Text(), nullable=True),
    sa.Column('creationDate', sa.Integer(), nullable=True),
    sa.Column('lastModified', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('my_index', 'notes', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
